version: '2.1'
orbs:
  node: circleci/node@5.1.0

defaults: &defaults
  docker:
    - image: cimg/python:3.10
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

jobs:
  deploy_app_to_railway:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project/
      - node/install:
          node-version: '21.1'
      - run: node --version
      - run: npm i -g @railway/cli
      - run:
          name: Deploy to Railway App
          command: |
            cd bankchurn-api 
            railway link 7648ccd4-feec-41fd-b460-cb0ff66fffdc cc4734e1-8dc0-43c1-adf4-67e59ee4ef9b
            railway up --detach


tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/

workflows:
  version: 1
  deploy_pipeline:
    jobs:
      - deploy_app_to_railway:
          filters:
            branches:
              only:
                - main
